[package]
name = "differ-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
rayon = "1.5.1"
serde = { version = "1.0.134", features = ["derive"] }
serde_json = "1.0.75"
walkdir = "2.3.2"
