[package]
name = "differ-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.0.10", features = ["derive"] }
colored = "2.0.0"
rayon = "1.5.1"
ssh2 = "0.9.3"
walkdir = "2.3.2"
